server:
  port: 8082
spring:
  application:
    name: image-storage
  sql:
    init:
      mode: always
  liquibase:
    change-log: db/changelog.xml
  r2dbc:
    username: root
    password: root
    url: r2dbc:postgresql://localhost:5432/postgres?schema=public
logging:
  level:
    org:
      springframework:
        data:
          r2dbc: DEBUG