spring:
  application:
    name: notification-sender-service
  mail:
    host: smtp.yandex.ru
    port: 25
    username: dmitry.kron20@yandex.ru
    password: wlmckqebahntidpa
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  kafka:
    consumer:
      group-id: some_id