spring:
  application:
    name: notification-sender-service
  mail:
    host: smtp.yandex.ru
    port: 25
    username: #почта
    password: #Пароль (в случае с яндексом пароль приложения, а не акка)
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  kafka:
    consumer:
      group-id: some_id